window.inspirationVideos = [
  {
    n: 1,
    g: "Literal POV → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Private texting distress → in-moment app use",
    p: "1M views · 11.8% like rate",
    views: 1000000,
    engagement: 11.8,
    a: "@ura_app",
    id: "7643354280879000850",
    u: "https://www.tiktok.com/@ura_app/video/7643354280879000850",
    img: "assets/library/1.jpg",
    hook: "An anxious-attachment texting moment creates the distress before the product appears.",
    transition: "The app opens while the person is still inside the situation.",
    demo: "One focused support interaction responds to the immediate emotional trigger.",
    payoff: "The problem, product role, and emotional movement are visible in one sequence."
  },
  {
    n: 2,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Panic episode → guided relief",
    p: "1.9M views · 8.6% like rate",
    views: 1900000,
    engagement: 8.6,
    a: "@ura_app",
    id: "7675941829807705362",
    u: "https://www.tiktok.com/@ura_app/video/7675941829807705362",
    img: "assets/library/es1.jpg",
    hook: "A woman wakes up experiencing a panic attack.",
    transition: "Once the emotional situation is established, the video hard-cuts into the app.",
    demo: "Breathing, grounding, and sensory exercises are shown as one guided sequence.",
    payoff: "The app confirms that the episode passed, making the state change explicit."
  },
  {
    n: 3,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Sensory overload → calm interface",
    p: "1.1M views · 18.4% like rate",
    views: 1100000,
    engagement: 18.4,
    a: "@ura_app",
    id: "7659674791795887378",
    u: "https://www.tiktok.com/@ura_app/video/7659674791795887378",
    img: "assets/library/es2.jpg",
    hook: "The opening visualizes a chaotic internal experience rather than explaining it.",
    transition: "The visual contrast between overload and the calm interface becomes the cut.",
    demo: "One structured guidance sequence replaces the chaos.",
    payoff: "The viewer immediately understands the movement from overwhelm toward control."
  },
  {
    n: 4,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Emotional scene → measurable state change",
    p: "748K views · 15.2% like rate",
    views: 748000,
    engagement: 15.2,
    a: "@ura_app",
    id: "7664025627351059720",
    u: "https://www.tiktok.com/@ura_app/video/7664025627351059720",
    img: "assets/library/es3.jpg",
    hook: "The video spends longer establishing the person’s distress.",
    transition: "The app appears at the point when the viewer needs an intervention.",
    demo: "A focused guided interaction is completed instead of showing the whole product.",
    payoff: "A visible reduction in intensity makes the result legible on screen."
  },
  {
    n: 5,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Distress montage → product protocol",
    p: "760.5K views · 19.1% like rate",
    views: 760500,
    engagement: 19.1,
    a: "@ura_app",
    id: "7659993249649839367",
    u: "https://www.tiktok.com/@ura_app/video/7659993249649839367",
    img: "assets/library/es4.jpg",
    hook: "A montage makes the emotional state recognizable without an original acted scene.",
    transition: "The montage cuts into the app once the shared feeling is clear.",
    demo: "Breathing, grounding, and check-in actions form one compact protocol.",
    payoff: "The product turns an undefined emotional state into a structured next sequence."
  },
  {
    n: 6,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Time-based discovery → generated meal plan",
    p: "367.3K views · 5.9% like rate",
    views: 367300,
    engagement: 5.9,
    a: "@mealswitholi",
    id: "7670924461457034518",
    u: "https://www.tiktok.com/@mealswitholi/video/7670924461457034518",
    img: "assets/library/r1.jpg",
    hook: "Been shopping at Aldi for five years and only now discovering the tool.",
    transition: "A one-second disbelief reaction cuts almost immediately into the app.",
    demo: "Store, budget, and food preferences are entered.",
    payoff: "The generated meal plan and organized shopping list become the ending."
  },
  {
    n: 7,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Fast discovery → complete generated output",
    p: "116.2K views · 6.1% like rate",
    views: 116200,
    engagement: 6.1,
    a: "@dallis.nourish",
    id: "7671023222829223198",
    u: "https://www.tiktok.com/@dallis.nourish/video/7671023222829223198",
    img: "assets/library/r2.jpg",
    hook: "Been shopping at Aldi for eight years and only now finding the app.",
    transition: "The reaction lasts roughly two seconds before the interface takes over.",
    demo: "Six simple inputs define the meal-planning request.",
    payoff: "A budgeted plan, recipe details, and grocery list justify the discovery reaction."
  },
  {
    n: 8,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Initial result → changed result → second reaction",
    p: "910.3K views · 9.2% like rate",
    views: 910300,
    engagement: 9.2,
    a: "@may.scrublife",
    id: "7677733265779805453",
    u: "https://www.tiktok.com/@may.scrublife/video/7677733265779805453",
    img: "assets/library/r4.jpg",
    hook: "The creator points excitedly at her calculated nursing pay.",
    transition: "The first result leads directly into changing the inputs.",
    demo: "More shifts are added inside the pay-calculation app.",
    payoff: "The higher total creates a second, justified reaction."
  },
  {
    n: 9,
    g: "Wall of Text → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Emotional paragraph → note action → widget result",
    p: "692.7K views · 19.1% like rate",
    views: 692700,
    engagement: 19.1,
    a: "@annasdiary02",
    id: "7668791530596863246",
    u: "https://www.tiktok.com/@annasdiary02/video/7668791530596863246",
    img: "assets/library/wtd1.jpg",
    hook: "A paragraph names the fear of losing a boyfriend who means everything to her.",
    transition: "After roughly seven seconds of simple bedroom footage, the video hard-cuts into the app.",
    demo: "The creator writes and saves one note.",
    payoff: "The note visibly appears on the phone widget."
  },
  {
    n: 10,
    g: "Wall of Text → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Emotional paragraph → customization → finished screen",
    p: "148K views · 18.9% like rate",
    views: 148000,
    engagement: 18.9,
    a: "@annasdiary02",
    id: "7674139548175043853",
    u: "https://www.tiktok.com/@annasdiary02/video/7674139548175043853",
    img: "assets/library/wtd2.jpg",
    hook: "A paragraph focuses on hating falling asleep without her boyfriend beside her.",
    transition: "The seven-second emotional setup cuts into lock-screen customization.",
    demo: "Two app widgets are added while the viewer watches the interface change.",
    payoff: "The completed lock screen closes the loop."
  },
  {
    n: 11,
    g: "Wall of Text → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Repeatable text hook → same product sequence",
    p: "219.4K views · 18% like rate",
    views: 219400,
    engagement: 18,
    a: "@annasdiary02",
    id: "7671897675171712270",
    u: "https://www.tiktok.com/@annasdiary02/video/7671897675171712270",
    img: "assets/library/wtd3.jpg",
    hook: "A different paragraph returns to the fear of losing her boyfriend.",
    transition: "The emotional setup again cuts into the widget flow.",
    demo: "The creator selects and adds two widgets.",
    payoff: "The finished lock screen shows that the format can keep the product sequence while changing the opening."
  },
  {
    n: 12,
    g: "Pure Wall of Text",
    roles: ["tone", "format"],
    roleLabel: "Tone + format reference",
    f: "Betrayal contradiction → debate",
    p: "832.7K views · 6.8% like rate",
    views: 832700,
    engagement: 6.8,
    a: "@legirltea",
    id: "7668644389882776862",
    u: "https://www.tiktok.com/@legirltea/video/7668644389882776862",
    img: "assets/library/2.jpg",
    hook: "A complete confession contrasts feeling close again with remembering that the truth would never have been volunteered.",
    transition: "No product appears; the paragraph remains over quiet kitchen footage.",
    demo: "No product action occurs in the source.",
    payoff: "Recognition and disagreement keep the thought active in the comments.",
    caveat: "Performance may partly come from controversy. The wording can feel judgmental toward people who remain or reconcile after betrayal."
  },
  {
    n: 13,
    g: "Pure Wall of Text",
    roles: ["tone", "format"],
    roleLabel: "Tone + format reference",
    f: "Silence feels safer than honesty",
    p: "1.9M views · 16.4% like rate",
    views: 1900000,
    engagement: 16.4,
    a: "@notesonhealingg",
    id: "7661999248828828942",
    u: "https://www.tiktok.com/@notesonhealingg/video/7661999248828828942",
    img: "assets/library/3.jpg",
    hook: "A paragraph names the point where silence feels safer because honest feelings no longer seem likely to be understood.",
    transition: "No product appears; the paragraph stays over a quiet nighttime drive.",
    demo: "No product action occurs in the source.",
    payoff: "The emotional experience is named precisely enough that viewers recognize themselves."
  },
  {
    n: 14,
    g: "Pure Wall of Text",
    roles: ["tone", "format"],
    roleLabel: "Tone + format reference",
    f: "Pain without losing kindness",
    p: "1.5M views · 22.6% like rate",
    views: 1500000,
    engagement: 22.6,
    a: "@notesonhealingg",
    id: "7676829686986542350",
    u: "https://www.tiktok.com/@notesonhealingg/video/7676829686986542350",
    img: "assets/library/4.jpg",
    hook: "An identity statement describes being hurt without allowing the experience to remove the ability to love deeply.",
    transition: "No product appears; the full paragraph remains over nighttime highway footage.",
    demo: "No product action occurs in the source.",
    payoff: "The thought resolves in a clear statement of identity rather than advice."
  }
];
