window.inspirationVideos = [
  {
    n: 1,
    g: "Literal POV → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Private texting distress → in-moment app use",
    p: "1.03M views",
    views: 1030000,
    engagement: 0,
    a: "@ura_app",
    id: "7643354280879000850",
    u: "https://www.tiktok.com/@ura_app/video/7643354280879000850",
    img: "assets/library/1.jpg",
    hook: "An anxious-attachment texting moment creates the distress before the product appears.",
    transition: "The app opens while the person is still inside the situation.",
    demo: "One focused support interaction responds to the immediate emotional trigger.",
    payoff: "The problem, product role, and emotional movement are visible in one sequence."
  },
  {
    n: 2,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Panic episode → guided relief",
    p: "",
    views: 0,
    engagement: 0,
    a: "@ura_app",
    id: "7675941829807705362",
    u: "https://www.tiktok.com/@ura_app/video/7675941829807705362",
    img: "assets/library/es1.jpg",
    hook: "A woman wakes up experiencing a panic attack.",
    transition: "Once the emotional situation is established, the video hard-cuts into the app.",
    demo: "Breathing, grounding, and sensory exercises are shown as one guided sequence.",
    payoff: "The app confirms that the episode passed, making the state change explicit."
  },
  {
    n: 3,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Sensory overload → calm interface",
    p: "",
    views: 0,
    engagement: 0,
    a: "@ura_app",
    id: "7659674791795887378",
    u: "https://www.tiktok.com/@ura_app/video/7659674791795887378",
    img: "assets/library/es2.jpg",
    hook: "The opening visualizes a chaotic internal experience rather than explaining it.",
    transition: "The visual contrast between overload and the calm interface becomes the cut.",
    demo: "One structured guidance sequence replaces the chaos.",
    payoff: "The viewer immediately understands the movement from overwhelm toward control."
  },
  {
    n: 4,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Emotional scene → measurable state change",
    p: "",
    views: 0,
    engagement: 0,
    a: "@ura_app",
    id: "7664025627351059720",
    u: "https://www.tiktok.com/@ura_app/video/7664025627351059720",
    img: "assets/library/es3.jpg",
    hook: "The video spends longer establishing the person’s distress.",
    transition: "The app appears at the point when the viewer needs an intervention.",
    demo: "A focused guided interaction is completed instead of showing the whole product.",
    payoff: "A visible reduction in intensity makes the result legible on screen."
  },
  {
    n: 5,
    g: "Emotional Scenario → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Distress montage → product protocol",
    p: "",
    views: 0,
    engagement: 0,
    a: "@ura_app",
    id: "7659993249649839367",
    u: "https://www.tiktok.com/@ura_app/video/7659993249649839367",
    img: "assets/library/es4.jpg",
    hook: "A montage makes the emotional state recognizable without an original acted scene.",
    transition: "The montage cuts into the app once the shared feeling is clear.",
    demo: "Breathing, grounding, and check-in actions form one compact protocol.",
    payoff: "The product turns an undefined emotional state into a structured next sequence."
  },
  {
    n: 6,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Time-based discovery → generated meal plan",
    p: "",
    views: 0,
    engagement: 0,
    a: "@mealswitholi",
    id: "7670924461457034518",
    u: "https://www.tiktok.com/@mealswitholi/video/7670924461457034518",
    img: "assets/library/r1.jpg",
    hook: "Been shopping at Aldi for five years and only now discovering the tool.",
    transition: "A one-second disbelief reaction cuts almost immediately into the app.",
    demo: "Store, budget, and food preferences are entered.",
    payoff: "The generated meal plan and organized shopping list become the ending."
  },
  {
    n: 7,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Fast discovery → complete generated output",
    p: "",
    views: 0,
    engagement: 0,
    a: "@dallis.nourish",
    id: "7671023222829223198",
    u: "https://www.tiktok.com/@dallis.nourish/video/7671023222829223198",
    img: "assets/library/r2.jpg",
    hook: "Been shopping at Aldi for eight years and only now finding the app.",
    transition: "The reaction lasts roughly two seconds before the interface takes over.",
    demo: "Six simple inputs define the meal-planning request.",
    payoff: "A budgeted plan, recipe details, and grocery list justify the discovery reaction."
  },
  {
    n: 8,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Reaction to a hack → checkout proof",
    p: "",
    views: 0,
    engagement: 0,
    a: "@sarahm.shops",
    id: "7666254261059161357",
    u: "https://www.tiktok.com/@sarahm.shops/video/7666254261059161357",
    img: "assets/library/r3.jpg",
    hook: "A provocative money-saving claim creates immediate curiosity.",
    transition: "The creator reacts over another video, then moves into the product flow.",
    demo: "She finds an item, copies an app-generated discount code, and applies it at checkout.",
    payoff: "The checkout price visibly drops before the app is named."
  },
  {
    n: 9,
    g: "Reaction → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "Initial result → changed result → second reaction",
    p: "",
    views: 0,
    engagement: 0,
    a: "@may.scrublife",
    id: "7677733265779805453",
    u: "https://www.tiktok.com/@may.scrublife/video/7677733265779805453",
    img: "assets/library/r4.jpg",
    hook: "The creator points excitedly at her calculated nursing pay.",
    transition: "The first result leads directly into changing the inputs.",
    demo: "More shifts are added inside the pay-calculation app.",
    payoff: "The higher total creates a second, justified reaction."
  },
  {
    n: 10,
    g: "Literal POV → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "POV conflict → hidden app role → proof",
    p: "",
    views: 0,
    engagement: 0,
    a: "@.wfhgirl",
    id: "7662126846535896351",
    u: "https://www.tiktok.com/@.wfhgirl/video/7662126846535896351",
    img: "assets/library/p1.jpg",
    hook: "POV: your boss abuses you, not realizing you’re recording.",
    transition: "The confrontation unfolds before the phone reveals that the app was already operating inside the scene.",
    demo: "The recording and transcription output are shown.",
    payoff: "A written transcript completes the premise and gives the employee proof."
  },
  {
    n: 11,
    g: "Literal POV → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "POV outcome first → method revealed",
    p: "",
    views: 0,
    engagement: 0,
    a: "@patrickstudiess",
    id: "7652520115342265613",
    u: "https://www.tiktok.com/@patrickstudiess/video/7652520115342265613",
    img: "assets/library/p2.jpg",
    hook: "POV: the exam results arrive and reveal a major academic comeback.",
    transition: "Celebration and reaction clips create curiosity about how the result happened.",
    demo: "The study app builds a personalized exam plan with quizzes and flashcards.",
    payoff: "The previously shown result gives the setup process meaning."
  },
  {
    n: 12,
    g: "Literal POV → Demo",
    roles: ["format", "product"],
    roleLabel: "Format + product reference",
    f: "POV interaction loop → app creates the joke",
    p: "",
    views: 0,
    engagement: 0,
    a: "@irene.learns.dutch",
    id: "7648961527575219488",
    u: "https://www.tiktok.com/@irene.learns.dutch/video/7648961527575219488",
    img: "assets/library/p3.jpg",
    hook: "POV: you finally unlocked the Dutch ‘G’.",
    transition: "The app is present from the start rather than revealed after the setup.",
    demo: "The creator repeats pronunciation attempts and receives corrections.",
    payoff: "A cough is mistaken for perfect pronunciation, creating the unexpected final response."
  },
  {
    n: 13,
    g: "Wall of Text → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Emotional paragraph → note action → widget result",
    p: "",
    views: 0,
    engagement: 0,
    a: "@annasdiary02",
    id: "7668791530596863246",
    u: "https://www.tiktok.com/@annasdiary02/video/7668791530596863246",
    img: "assets/library/wtd1.jpg",
    hook: "A paragraph names the fear of losing a boyfriend who means everything to her.",
    transition: "After roughly seven seconds of simple bedroom footage, the video hard-cuts into the app.",
    demo: "The creator writes and saves one note.",
    payoff: "The note visibly appears on the phone widget."
  },
  {
    n: 14,
    g: "Wall of Text → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Emotional paragraph → customization → finished screen",
    p: "",
    views: 0,
    engagement: 0,
    a: "@annasdiary02",
    id: "7674139548175043853",
    u: "https://www.tiktok.com/@annasdiary02/video/7674139548175043853",
    img: "assets/library/wtd2.jpg",
    hook: "A paragraph focuses on hating falling asleep without her boyfriend beside her.",
    transition: "The seven-second emotional setup cuts into lock-screen customization.",
    demo: "Two app widgets are added while the viewer watches the interface change.",
    payoff: "The completed lock screen closes the loop."
  },
  {
    n: 15,
    g: "Wall of Text → Demo",
    roles: ["format", "product", "tone"],
    roleLabel: "Format + product + tone reference",
    f: "Repeatable text hook → same product sequence",
    p: "",
    views: 0,
    engagement: 0,
    a: "@annasdiary02",
    id: "7671897675171712270",
    u: "https://www.tiktok.com/@annasdiary02/video/7671897675171712270",
    img: "assets/library/wtd3.jpg",
    hook: "A different paragraph returns to the fear of losing her boyfriend.",
    transition: "The emotional setup again cuts into the widget flow.",
    demo: "The creator selects and adds two widgets.",
    payoff: "The finished lock screen shows that the format can keep the product sequence while changing the opening."
  },
  {
    n: 16,
    g: "Feature-first",
    roles: ["product"],
    roleLabel: "Product reference",
    f: "Live input → visual guidance → improved output",
    p: "",
    views: 0,
    engagement: 0,
    a: "@dokacam_official",
    id: "7658684346307529997",
    u: "https://www.tiktok.com/@dokacam_official/video/7658684346307529997",
    img: "assets/library/f1.jpg",
    hook: "The video starts inside the camera product with a live sunset shot.",
    transition: "No separate lifestyle setup is needed because the feature creates the curiosity.",
    demo: "The interface analyzes framing, gives zoom directions, and recommends a treatment.",
    payoff: "The finished photograph makes the product’s value visible."
  },
  {
    n: 17,
    g: "Pure Wall of Text",
    roles: ["tone", "format"],
    roleLabel: "Tone + format reference",
    f: "Betrayal contradiction → debate",
    p: "832.6K views · 6.8% like rate",
    views: 832600,
    engagement: 6.8,
    a: "@legirltea",
    id: "7668644389882776862",
    u: "https://www.tiktok.com/@legirltea/video/7668644389882776862",
    img: "assets/library/2.jpg",
    hook: "A complete confession contrasts feeling close again with remembering that the truth would never have been volunteered.",
    transition: "No product appears; the paragraph remains over quiet kitchen footage.",
    demo: "No product action occurs in the source.",
    payoff: "Recognition and disagreement keep the thought active in the comments.",
    caveat: "Performance may partly come from controversy. The wording can feel judgmental toward people who remain or reconcile after betrayal."
  },
  {
    n: 18,
    g: "Pure Wall of Text",
    roles: ["tone", "format"],
    roleLabel: "Tone + format reference",
    f: "Silence feels safer than honesty",
    p: "1.86M views · 16.7% like rate",
    views: 1860000,
    engagement: 16.7,
    a: "@notesonhealingg",
    id: "7661999248828828942",
    u: "https://www.tiktok.com/@notesonhealingg/video/7661999248828828942",
    img: "assets/library/3.jpg",
    hook: "A paragraph names the point where silence feels safer because honest feelings no longer seem likely to be understood.",
    transition: "No product appears; the paragraph stays over a quiet nighttime drive.",
    demo: "No product action occurs in the source.",
    payoff: "The emotional experience is named precisely enough that viewers recognize themselves."
  },
  {
    n: 19,
    g: "Pure Wall of Text",
    roles: ["tone", "format"],
    roleLabel: "Tone + format reference",
    f: "Pain without losing kindness",
    p: "1.47M views · 23% like rate",
    views: 1470000,
    engagement: 23,
    a: "@notesonhealingg",
    id: "7676829686986542350",
    u: "https://www.tiktok.com/@notesonhealingg/video/7676829686986542350",
    img: "assets/library/4.jpg",
    hook: "An identity statement describes being hurt without allowing the experience to remove the ability to love deeply.",
    transition: "No product appears; the full paragraph remains over nighttime highway footage.",
    demo: "No product action occurs in the source.",
    payoff: "The thought resolves in a clear statement of identity rather than advice."
  }
];
